chore: release v4.1.0
dequelabs/axe-core-maven-html pull request #125
Opened 2020-12-16 20:21 UTC by AdnoC

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [ ] Code is reviewed for security

2020-12-16 21:24 UTC, jeeyyy commented
I see the below in CI.

```
[WARNING] Rule 1: org.sonatype.ossindex.maven.enforcer.BanVulnerableDependencies warned with message:
Detected 1 vulnerable components:
  junit:junit:jar:4.13:test; https://ossindex.sonatype.org/component/pkg:maven/junit/junit@4.13?utm_source=ossindex-client&utm_medium=integration&utm_content=1.1.1
    * [CVE-2020-15250] In JUnit4 from version 4.7 and before 4.13.1, the test rule TemporaryFolder cont... (5.5); https://ossindex.sonatype.org/vuln/7ea56ad4-8a8b-4e51-8ed9-5aad83d8efb1?component-type=maven&component-name=junit.junit&utm_source=ossindex-client&utm_medium=integration&utm_content=1.1.1
```

2020-12-16 21:25 UTC, jeeyyy requested changes
See above comment

2020-12-16 22:14 UTC, AdnoC commented
If it is a warning it is from a test dependency and has no bearing no downstream packages. Updated anyways.

2020-12-17 14:16 UTC, jeeyyy approved these changes
## Release Audit
- https://github.com/dequelabs/axe-core-maven-html/pull/124
- https://github.com/dequelabs/axe-core-maven-html/pull/127
- https://github.com/dequelabs/axe-core-maven-html/pull/121

2020-12-17 14:18 UTC, merged