chore: add bug report and feature request issue templates
dequelabs/axe-core-maven-html pull request #446
Opened 2024-03-25 16:33 UTC by scottmries

Closes: #445

2024-03-25 16:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dequelabs/axe-core-maven-html?pullRequest=446) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dequelabs/axe-core-maven-html?pullRequest=446) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dequelabs/axe-core-maven-html?pullRequest=446) it.</sub>

2024-03-25 21:50 UTC, straker requested changes

2024-03-25 21:50 UTC, straker commented on .github/ISSUE_TEMPLATE/bug-report.md
> +- Product: [e.g. linter-server]
For our open source projects, we should list an actual example product rather than copy/paste and list products that don't apply to this repo.

2024-03-30 08:56 UTC, tealamore commented on .github/ISSUE_TEMPLATE/bug-report.md
> +- Product: [e.g. axe-core]
shouldn't this be axe-core-maven-html this the issue would be opened for this repo?

2024-04-01 21:14 UTC, straker approved these changes

2024-04-01 21:23 UTC, merged